


services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/Diagnosoft_API
      # - /Diagnosoft_API/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    restart: unless-stopped
